# permissions for end users to view terraforms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: terraform-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: terraform-operator
    app.kubernetes.io/part-of: terraform-operator
    app.kubernetes.io/managed-by: kustomize
  name: terraform-viewer-role
rules:
- apiGroups:
  - infra.terraform.zombor.net
  resources:
  - terraforms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.terraform.zombor.net
  resources:
  - terraforms/status
  verbs:
  - get
